# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `load_path`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

# Suppress duplicate constant warnings from bundled gems conflicting with Ruby 4.0 built-ins
# (e.g. strscan-3.1.8 vs Ruby's built-in strscan-3.1.6)
Warning.extend(Module.new do
  def warn(msg, category: nil, **kwargs)
    return if msg.include?("already initialized constant StringScanner::")
    super
  end
end)

RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the RSpec
    # expectation syntax available to all example groups.
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as flexmock/mocha) if you prefer.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the config option exists leaning towards
  # what will be its eventual default).
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # The settings below are suggested to provide a good initial experience
  # with RSpec, but feel free to customize to your needs if you wish.
  # # This allows you to limit a spec run to individual examples or groups
  # # you care about by tagging them with `focus` metadata. When nothing
  # # is tagged with `focus`, all examples get run. RSpec also provides
  # # aliases for `it`, `describe`, etc. which include `:focus` metadata:
  # #
  # #   it 'does something' { }
  # #   xdescribe 'doing something else' do
  # #     it 'has examples'
  # #   end
  # #
  # # Aliases in this file will end up in RSpec examples.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure this to be able to cope with your test suite timing out:
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://relishapp.com/rspec/rspec-core/docs/configuration/zero-monkey-patching-mode
  # config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to have the spec/examples.txt file open in the
  # editor. However, when running an arbitrary subset of specs, this could
  # be a time-consuming operation for some users. For this reason, we suggest
  # turning it off by default.
  # config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is listed in the output and can be used again with
  # --seed:
  #   --seed 1234
  config.order = :random

  # Seed global randomization in this process using the seed clause in the
  # CLI.  Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to the randomization by passing the same `--seed`
  # value as the environment variable like:
  #
  #   --seed=<see output when you run this command>
  #
  #     --seed 1234
  Kernel.srand config.seed
end
